# Generated by Django 5.2.3 on 2025-06-28 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('place_img', models.ImageField(upload_to='places_images/')),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(default='India', max_length=30)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'Places',
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='tp_img/')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('package_type', models.CharField(choices=[('Single', 'Single Destination'), ('Multiple', 'Multiple Destinations')], default='Single', max_length=10)),
                ('duration_days', models.PositiveIntegerField()),
                ('duration_nights', models.PositiveIntegerField()),
                ('base_price', models.FloatField()),
                ('discount', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_order', models.PositiveIntegerField(default=1)),
                ('days_in_destination', models.PositiveIntegerField()),
                ('dest_image', models.ImageField(upload_to='dest_images/')),
                ('tour_type', models.CharField(choices=[('Group', 'Group'), ('Regular', 'Regular'), ('Luxury', 'Luxury'), ('Honeymoon', 'Honeymoon')], max_length=10)),
                ('description', models.TextField(max_length=1000)),
                ('arrival_point', models.CharField(max_length=50)),
                ('departure_point', models.CharField(max_length=50)),
                ('accommodation', models.TextField(max_length=200)),
                ('things_to_do', models.TextField(max_length=500)),
                ('special_attractions', models.TextField(blank=True, max_length=500, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.places')),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='booking.tourpackage')),
            ],
            options={
                'ordering': ['destination_order'],
                'unique_together': {('tour_package', 'place')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(editable=False, max_length=25, unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('travel_start_date', models.DateField()),
                ('adults', models.PositiveIntegerField()),
                ('kids_5_12', models.PositiveIntegerField(default=0)),
                ('kids_b_5', models.PositiveIntegerField(default=0)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('advance_amount', models.FloatField(default=0.0)),
                ('remaining_amount', models.FloatField(blank=True, null=True)),
                ('booking_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('In Progress', 'In Progress')], default='Pending', max_length=20)),
                ('special_requests', models.TextField(blank=True, max_length=500, null=True)),
                ('dietary_requirements', models.CharField(blank=True, max_length=100, null=True)),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.tourpackage')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_day_number', models.PositiveIntegerField()),
                ('package_day_number', models.PositiveIntegerField()),
                ('day_title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('morning_activities', models.TextField(blank=True, max_length=300, null=True)),
                ('afternoon_activities', models.TextField(blank=True, max_length=300, null=True)),
                ('evening_activities', models.TextField(blank=True, max_length=300, null=True)),
                ('meals_included', models.CharField(blank=True, max_length=50, null=True)),
                ('local_transportation', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_itinerary', to='booking.destination')),
            ],
            options={
                'ordering': ['package_day_number'],
                'unique_together': {('destination', 'local_day_number')},
            },
        ),
        migrations.CreateModel(
            name='PackageItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('day_title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('activities', models.TextField(blank=True, max_length=500, null=True)),
                ('meals_included', models.CharField(blank=True, max_length=50, null=True)),
                ('accommodation_details', models.CharField(blank=True, max_length=100, null=True)),
                ('transportation', models.CharField(blank=True, max_length=100, null=True)),
                ('optional_activities', models.TextField(blank=True, max_length=300, null=True)),
                ('is_travel_day', models.BooleanField(default=False)),
                ('current_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_days', to='booking.destination')),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_itinerary', to='booking.tourpackage')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('tour_package', 'day_number')},
            },
        ),
    ]
