# Generated by Django 5.2.3 on 2025-06-29 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tour_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.tourpackage'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='tour_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='booking.tourpackage'),
        ),
    ]
